language: java

jdk:
  - oraclejdk8

after_success:
  - mvn clean javadoc:jar
  - mvn deploy --settings settings.xml

branches:
  only:
    - master
      # Build tags that match this regex in addition to building the master branch.
    - /^jenkins-keycloak-plugin-[0-9]+\.[0-9]+\.[0-9]+/
